services:
  - type: web
    name: igreja-ceadrei
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: ceasdrei
